name: Deploy Frontend To VPS

on:
  push:
    branches:
      - v2_frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |

            echo "Starting deployment..."

            #Go to project folder
            cd /home/mohamed/apps/residence_siby/frontend || exit 1

            # Pull latest changes
            git reset --hard HEAD || exit 1
            git config pull.rebase false
            git pull origin/v2_frontend || exit 1

            echo "Pull was successful, installing dependencies..."
            npm install
            npm run build || exit 1

            echo "Dependencies installed, Restart frontend (Nginx)..."
            sudo systemctl restart nginx
            sudo nginx -t


            echo "Deployment completed successfully!"
