name: Deploy Backend To VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |

            echo "Starting deployment..."

            #Go to project folder
            cd /home/mohamed/apps/residence_siby/backend || exit 1

            # Pull latest changes
            git reset --hard
            git pull origin master

            echo "Pull was successful, installing dependencies..."
            npm install

            echo "Dependencies installed, Restart backend (PM2)..."
            pm2 restart backend_residence


            echo "Deployment completed successfully!"
